version: '3.1'
services:
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    entrypoint:
      sh -c "
        echo 'CREATE DATABASE IF NOT EXISTS $MYSQL_DB; CREATE DATABASE IF NOT EXISTS ${MYSQL_DB}_test;' > /docker-entrypoint-initdb.d/init.sql;
        /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      "

  adminer:
    depends_on:
      - db
    image: adminer
    ports:
      - 8090:8080
